services:
  authentication:
    image: authentication
    build:
      context: .
      dockerfile: Authentication/Dockerfile

  apigetwayservice:
    image: apigetwayservice
    build:
      context: .
      dockerfile: ApiGetwayService/Dockerfile
    ports:
      - '61000:8080'

  customer:
    image: customer
    build:
      context: .
      dockerfile: Customer/Dockerfile

  order:
    image: order
    build:
      context: .
      dockerfile: Order/Dockerfile

  product:
    image: product
    build:
      context: .
      dockerfile: Product/Dockerfile

  inventory:
    image: inventory
    build:
      context: .
      dockerfile: Inventory/Dockerfile

